---
title: "7. Sensitivity Analysis"
---

# Sensitivity Analyses

Once users have conducted their propensity score analysis, it is important to perform sensitivity analyses afterwards, in order to examine the robustness of their causal claims. Whilst propensity score methods aim to balance observed covariates between groups, accounting for measured confounding, it cannot address unmeasured confounding variables that may continue to have an impact on the results.

There are several means of conducting sensitivity analyses, a selection of which are available in DigiCAT at present, for continuous and binary outcomes.

## Rosenbaum’s Bounds 

Rosenbaum's bounds sensitivity analysis looks at how susceptible the findings of the user’s matched observational study are to possible hidden bias. It obtains the matched pairs of both treated and control units and calculates the difference in outcomes per pair.The method introduces a sensitivity parameter, Gamma (Γ), capturing the possible effect of hidden bias. When Γ = 1, it assumes no unmeasured confounding, as if the treatment assignment were perfectly random. As Γ increases, it allows for the possibility that the treated units had a greater likelihood of receiving treatment due to unmeasured variables. For example, if Γ = 2, it assumes that treated units could have been up to twice as likely to receive treatment due to some unobserved factor. In DigiCAT, the underlying packages used, by default, compute results for Γ values from 1 to 6, incrementing by 1. 
Rosenbaum’s method tests the null hypothesis (no treatment effect) under these different levels of Γ (1-6). It calculates upper and lower bounds on the returned p-values, yielding a measure of how sensitive the results are to bias. If p-values remain significant for large values of Γ, the findings are thought to be robust to unmeasured confounding. Conversely, if the p-values become non-significant at low Γ values, the results are highly sensitive, thus even a small amount of hidden bias could invalidate the user’s findings.  

## E-Values 

E-values are a further option for sensitivity analysis in DigiCAT, and these values help quantify the minimum strength of association that an unmeasured confounder would need to have with both the exposure/treatment and the outcome of interest, in order to explain away an observed association between a treatment and an outcome. Large E-values would suggest a robust observed association, as it suggests a strong unmeasured confounder is necessary to explain the effect. Therefore, small E-values indicate that the results are more sensitive to unmeasured confounding. E-values can be computed depending on a point estimate or confidence intervals, and both are available within DigiCAT. 
